// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7HV2x7YDfOJo_PUF4L9Afffb4rnC5lps',
    appId: '1:497803329641:web:9458451c61ad96cd2fe2f8',
    messagingSenderId: '497803329641',
    projectId: 'foodio-23fa4',
    authDomain: 'foodio-23fa4.firebaseapp.com',
    storageBucket: 'foodio-23fa4.appspot.com',
    measurementId: 'G-PMQ8BM3HBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADDbN9h0Sv6sTTXfqJ6haUOL1yhSGbeUk',
    appId: '1:497803329641:android:f10b6a6489653fe52fe2f8',
    messagingSenderId: '497803329641',
    projectId: 'foodio-23fa4',
    storageBucket: 'foodio-23fa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZKQ9olt6KMajWfGVZ7Scioov8SB7P-hE',
    appId: '1:497803329641:ios:030662d4d5e298322fe2f8',
    messagingSenderId: '497803329641',
    projectId: 'foodio-23fa4',
    storageBucket: 'foodio-23fa4.appspot.com',
    iosBundleId: 'com.abishekab.foodio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZKQ9olt6KMajWfGVZ7Scioov8SB7P-hE',
    appId: '1:497803329641:ios:030662d4d5e298322fe2f8',
    messagingSenderId: '497803329641',
    projectId: 'foodio-23fa4',
    storageBucket: 'foodio-23fa4.appspot.com',
    iosBundleId: 'com.abishekab.foodio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7HV2x7YDfOJo_PUF4L9Afffb4rnC5lps',
    appId: '1:497803329641:web:1493de44171248d22fe2f8',
    messagingSenderId: '497803329641',
    projectId: 'foodio-23fa4',
    authDomain: 'foodio-23fa4.firebaseapp.com',
    storageBucket: 'foodio-23fa4.appspot.com',
    measurementId: 'G-3TS7RYHLG4',
  );
}
